services:
  jenkins:
    container_name: jenkins
    image: davenchy/depi-project-jenkins:latest
    build:
      context: .
      dockerfile: jenkins_dockerfile
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
  gogs:
    container_name: gogs
    image: davenchy/gogs
    build:
      context: .
      dockerfile: gogs_dockerfile
    restart: on-failure
    ports:
      - 3000:3000
      - 3022:22
    volumes:
      - ./gogs:/data
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: on-failure
    user: "1000:1000"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus-data/:/prometheus
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: on-failure
    user: "1000:1000"
    ports:
      - 3001:3000
    volumes:
      - ./grafana:/var/lib/grafana
